### ISSUE TITLE
一部のユニークなEffectにis_uniqueフラグが立たない

### ISSUE THREAD

**Issue by answer-d** [answer-d/lol_gold_efficiency#2]
ドーナツたべたい

**Comment by answer-d** [comment]
該当アイテム一覧
- ウォッチャーのレムナント	3092
- ウォッチャーのレムナント	3092
- エンシェントコイン	3301
- オームレッカー	3056
- ガーゴイルストーンプレート	3193
- コラプトポーション	2033
- サルベーション	3382
- ジ＝ロット・ポータル	3512
- ジークコンバージェンス	3050
- シュレリアの思念	2065
- シルバーサッシュ	3140
- ストップウォッチ	2420
- ストップウォッチ	2423
- スペルシーフエッジ	3303
- セラフ・エンブレイス	3040
- セラフ・エンブレイス	3048
- ゾーニャの砂時計	3157
- ゾーニャの遡時計	3386
- ソラリのサークレット	3383
- ソラリのロケット	3190
- ターゴンの腕輪	3097
- タイタン・ハイドラ	3748
- ティアマット	3077
- ドランリング	1056
- ノマドのメダル	3096
- ハンターポーション	2032
- ビルジウォーター・カトラス	3144
- フロストファング	3098
- ヘクステック・ガンブレード	3146
- マーキュリアル・シミター	3139
- ミカエルのるつぼ	3222
- ラヴァナス・ハイドラ	3074
- ランデュイン・オーメン	3143
- リデンプション	3107
- ルインドキング・ブレード	3153
- レリックシールド	3302
- 騎士の誓い	3109
- 詰め替えポーション	2031
- 神髄のレムナント	3401
- 超越者のレムナント	3069
- 統率の旗	3060
- 妖夢の霊剣	3142

**Comment by domahoki** [comment]
ユニークの判定を変えたため対応できたはず
